
---
title: "MARS assessment summary"
subtitle: Tables and Figures
date: "`r Sys.Date()`"
output:
  html_document:
    highlight: rstudio
    df_print: paged
---

<style type="text/css">
h1 { /* Header 1 */
  font-size: 24px;
}
</style>

```{r setup, include = FALSE, echo = FALSE}
library(dplyr)
knitr::opts_chunk$set(
  collapse = TRUE, echo = FALSE, message = FALSE,
  fig.width = 6, fig.height = 4.5, out.width = "650px", comment = "#>"
)
```

# NAME {.tabset}

## Parameters {.tabset}

### Summary 

```{r sdreport}
if (length(x@SD)) summary(x) %>% round(4) %>% as.data.frame()
```

### Correlation

```{r sdcorr}
if (length(x@SD) && length(x@SD$env$corr.fixed)) as.data.frame(x@SD$env$corr.fixed)
```

<!-- *ADD HESSIAN RMD* -->

## Fishery {.tabset}

<!-- *ADD FISHERY RMD* -->

<!-- *ADD SURVEY RMD* -->

<!-- *ADD SC RMD* -->

## Close-kin

<!-- *ADD TAG MOV RMD* -->

## Stock dynamics {.tabset}

### All stocks

```{r SB, fig.cap="Spawning output."}
plot_S(x, by = "stock")
```

```{r B, fig.cap="Total biomass."}
plot_B(x, by = "stock")
```

```{r FF, fig.cap="Instantaneous fishing mortality (per year)."}
plot_Fstock(x)
```

```{r R, fig.cap="Recruitment."}
plot_R(x)
```

```{r recdist, fig.cap="Distribution of recruitment by region per stock."}
plot_recdist(x)
```

<!-- *ADD SRR RMD* -->

<!-- *ADD STOCK REGION RMD* -->

<!-- *ADD MOVEMENT RMD* -->


## About

This report was generated on: `r Sys.time()`<br />
MARS version `r packageVersion("MARS")`<br />
`r R.version.string`
